# apiVersion: v1
# kind: Namespace
# metadata:
#   name: johnhedman

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: express-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: express-app
          image: "johnhedman/express-app:p3"
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          resources:
              limits:
                memory: "8G"
                cpu: "2000m"
              requests:
                memory: "1G"
                cpu: "1000m"
