apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jhedman-eksctl-config-role
  region: us-west-2

vpc:
  subnets:
    public:
      us-west-2a: { id: subnet-028494fe57ede80d3 }
      us-west-2b: { id: subnet-0276f0ec725968655 }
      us-west-2c: { id: subnet-0f49a26c0b3354f7b }
  securityGroup: "sg-0c03411158eb72748"
  sharedNodeSecurityGroup: "sg-0c03411158eb72748"

iam:
  serviceRoleARN: "arn:aws:iam::707566951618:role/jhedman-eks-cluster-role"

nodeGroups:
  - name: jhedman-eks-workers
    labels:
      role: workers
    instanceType: t2.micro
    desiredCapacity: 2
    volumeSize: 32
    securityGroups:
      attachIDs:
        - "sg-080f33e18f3d1152d"
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/authorized_keys
    iam:
      instanceProfileARN: "arn:aws:iam::707566951618:instance-profile/jhedman-ec2-role"
      instanceRoleARN: "arn:aws:iam::707566951618:role/jhedman-ec2-role"
